### ISSUE TITLE
Received error: ModuleNotFoundError: No module named 'plugins.o365'

### ISSUE THREAD

**Issue by stevesec** [knavesec/CredMaster#17]
When running this with the "O365" plugin, receive an error stating: ModuleNotFoundError: No module named 'plugins.o365'.

Current Python version 3.10.6

Steps to reproduce:
1. Git clone recent release
2. Run command as normal python3 credmaster.py -u <email.txt> -p <password.txt> --access_key '' --secret_access_key ''
3. Receive output

![credmaster](https://user-images.githubusercontent.com/80222096/190421266-cc2a0929-0723-4682-ae1c-705e357912ea.png)

**Comment by knavesec** [comment]
@stevesec Attempted to recreate this on a fresh VM but this worked fine for me. Steps:

1. `git clone https://github.com/knavesec/CredMaster`
2. `cd CredMaster`
3. `pip3 install -r requirements.txt`
4. `python3 credmaster.py --access_key "key" --secret_access_key "key" -u users.txt -p passwords.txt --plugin o365`

All functioned properly. I would recommend removing your instance and recloning the repo. If that doesn't work, there are a few things you can do to troubleshoot. 

1. Verify in the `plugins` folder there is an `o365` folder
2. Verify that in that `o365` folder, there is an `__init__.py` file, as that is what that `import_module` function is looking for

If neither of those work, please let me know

**Comment by stevesec** [comment]
@knavesec seems like it was a Python build issue with my setup. 

Thank you for your response.

**Comment by knavesec** [comment]
Glad it was resolved, thanks for the report!
