### ISSUE TITLE
Add ability to specify region

### ISSUE THREAD

**Issue by rmrf-sl4sh** [knavesec/CredMaster#19]
Is it possible to add the ability to specify a region?

**Comment by knavesec** [comment]
This is on the todo list, thanks for bringing this up! In terms of design, I will plan to implement it so that regardless of thread count it will spin up the API in the same region

**Comment by knavesec** [comment]
@rmrf-sl4sh Added in Dev branch in commit [933af36](https://github.com/knavesec/CredMaster/commit/933af36744a87e9fd91fd5a59b27a8ce8b20c7a0), will be merged into Main soon enough. 

Will be closed when main is merged

**Comment by rmrf-sl4sh** [comment]
Thanks!
