### ISSUE TITLE
Error with random.py when not specifying UA file

### ISSUE THREAD

**Issue by jsarkisian** [knavesec/CredMaster#3]
Awesome tool!

Quick thing, it errors out if you do not specify a file with user agents:

![image](https://user-images.githubusercontent.com/46200265/112059285-0a28be00-8b32-11eb-8fac-afac91f773e1.png)

Is this file a necessity for the tool to function? Seems like the intent is to use a random one if this is not specified.

Thanks!

**Comment by knavesec** [comment]
Hey, thanks for the bug report! Fixed in the most recent commit, just a cursory error on my part. Happy hunting!
