### ISSUE TITLE
Required Python3 version?

### ISSUE THREAD

**Issue by grandmerchant** [knavesec/CredMaster#34]
Getting the following error on a fresh install of Credmaster. Curious if there is a specific python3 version that is required for usage?

![image](https://user-images.githubusercontent.com/34313634/214439464-efd70527-7368-4739-a3d2-3f823c6e6544.png)

I'm on python 3.10.4

Have only encountered this issue so far using the Okta plugin.

**Comment by ZephrFish** [comment]
Have you got more output such as your CLI switches and config file used? The version of python3 shouldn't matter and I've tested on 3.x - 3.8, 3.9, 3.10 and 3.10.4

**Comment by ZephrFish** [comment]
Try it with `-t 1` as okta is limited to one thread

**Comment by ZephrFish** [comment]
if you're still getting errors with the thread count added I'll look into the module

**Comment by ZephrFish** [comment]
> -t 1 fixed it! Thank you :)

I'll look into editing the module anyways to add eloquent error checking 😄
