### ISSUE TITLE
o365enum module creates the output file, then checks if it exists, then dies because it exists

### ISSUE THREAD

**Issue by TheToddLuci0** [knavesec/CredMaster#38]
![image](https://user-images.githubusercontent.com/26094248/217866652-8abb7b58-9525-4d39-a725-f325f029493f.png)

Not sure if it affects any other modules, but it completely breaks o365enum.

**Comment by knavesec** [comment]
This behavior should only be happening when incorrect AWS auth args are passed to the function, but it should stop there rather than die on file check. Fixing in new commit
