### ISSUE TITLE
NameError: name 'random' is not defined

### ISSUE THREAD

**Issue by jsarkisian** [knavesec/CredMaster#5]
After closing issue [#3](https://github.com/knavesec/CredMaster/issues/3), I pulled the latest code and now have a new error:

![image](https://user-images.githubusercontent.com/46200265/112174620-ef575780-8bcc-11eb-91d4-45ddef6be783.png)

Thanks!

**Comment by jsarkisian** [comment]
Found issue for future fix:

`plugins/o365/__init__.py` was missing `import random` at top

**Comment by knavesec** [comment]
Catching everything I see! Fixed in latest commit, appreciate it!
