### ISSUE TITLE
Wiki Permissions

### ISSUE THREAD

**Issue by LukeLauterbach** [knavesec/CredMaster#52]
I'd love to be able to build the wiki out, and correct a few minor issues (like the capitalization of "httpbrute" in the example command for the HTTP Brute module). Has any consideration been made to changing the Wiki permissions to public ([Link](https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis))?

**Comment by LukeLauterbach** [comment]
Another example: it'd be great to warn folks that that Basic Auth has been disabled on most O365 tenants, so the O365 plugin is unlikely to work on the majority of tenants anymore ([Source](https://support.microsoft.com/en-us/topic/outlook-2016-implementation-of-autodiscover-0d7b2709-958a-7249-1c87-434d257b9087)).

**Comment by knavesec** [comment]
I don't want to open the wiki up to anyone as for the "least privilege necessary". If you'd like to make changes, feel free to make suggestions here and I'll add them in

HTTPBrute capitalization fixed, and note added to o365 plugin. Let me know if there are any more changes you'd like reflected, else I'll close the issue
