### ISSUE TITLE
Fortinet Plugin : 500 internal error

### ISSUE THREAD

**Issue by Arasteus** [knavesec/CredMaster#57]
Hello,

The Fortinet VPN plugin does not seem to work, for each request i receive a 500 internal error.
I tried to modify the headers or such but to no avail.

Do everybody have the same problem?

Thank you

**Comment by knavesec** [comment]
I unfortunately can't reproduce that error. It may be an issue with the specific instance of fortinet or an issue with a recent update. Unless there is additional context provided, I can't act on this. Leaving open in case others have similar issues
