### ISSUE TITLE
Delay problems

### ISSUE THREAD

**Issue by PocketDC** [knavesec/CredMaster#58]
It's entirely possible I'm not actually understanding the configs, but running with a config file of this:
![image](https://github.com/knavesec/CredMaster/assets/29924527/90c60edf-95e9-451f-b796-c4376c0a8a16)
I end up with the spray going, but then after it cycles through the usernames with a single password it then sleeps for 30 minutes.
![image](https://github.com/knavesec/CredMaster/assets/29924527/b0337c0d-8553-472f-842c-1f3d22d44894)

Shouldn't it be doing 4 different passwords and then sleeping for 30 minutes?

**Comment by knavesec** [comment]
@PocketDC good call out, small bug in the input error handling had it defaulting to 1 password, similar bug with the threading as well. Should be fixed in [2fd6db7](https://github.com/knavesec/CredMaster/commit/2fd6db7e0b4130e7e33a7e560fe5d051441971db)
