### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by aquinn-r7** [knavesec/CredMaster#59]
Hey there, just bringing it to your attention, the recent change to the threads default value is causing errors if the threads param is not specified.  I fixed it on my end by reverting the change to 'None' for the default variable back to 1.

`Traceback (most recent call last):
  File "/home/kali/tools/CredMaster/credmaster.py", line 713, in <module>
    CredMaster(args, pluginargs)
  File "/home/kali/tools/CredMaster/credmaster.py", line 54, in __init__
    self.Execute(args)
  File "/home/kali/tools/CredMaster/credmaster.py", line 207, in Execute
    valid, errormsg, pluginargs = validator.validate(pluginargs, args)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/tools/CredMaster/plugins/okta/__init__.py", line 14, in validate
    if args.threads == 1 or (args.threads > 1 and 'force' in pluginargs.keys()):
                             ^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'`

**Comment by knavesec** [comment]
Fixed in https://github.com/knavesec/CredMaster/commit/87012c237910b15aa57f5abc370e74b06c24a973

Thanks for the report!
