### ISSUE TITLE
Strange uname/password/API error after recent update

### ISSUE THREAD

**Issue by jsarkisian** [knavesec/CredMaster#6]
**Command:**

`python3 credmaster.py --plugin okta -u users.txt -p passwords.txt --access_key KEY --secret_access_key KEY --url ORG.okta.com`

Prior to the updates within the last week or so, this worked as expected. Now with that same command, I get the following error:

`Please provide plugin & username/password information, or provide API utility options (api_list/api_destroy/clean)`

Thank you!

**Comment by knavesec** [comment]
Fixed in commit 0e9ba64, thanks for reporting!
