### ISSUE TITLE
o365 plugin does not work anymore

### ISSUE THREAD

**Issue by TwistedSim** [knavesec/CredMaster#68]
Hello,

I recently found out the the o365 module uses the autodiscover login (https://autodiscover-s.outlook.com) with BasicAuth to do the spraying. Recently, Microsoft have block Basic Auth authentication  on all tenant (see https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online). 

Is there plans to change the login method used by the module to fix this ?

Thanks

**Comment by alecmoran1** [comment]
Interesting. I opened a similar issue: https://github.com/knavesec/CredMaster/issues/67. Do you think what I am seeing is because of what actually Microsoft implemented?

**Comment by kpomeroy1979** [comment]
Confirming here that with valid creds Credmaster still says authentication failed using the o365 plugin.

**Comment by TwistedSim** [comment]
I think the best alternative is to use the MSOL plugin.

**Comment by knavesec** [comment]
Hey everyone, you're all correct, it does appear that the `o365` plugin is dead, may it rest in peace. I'll update the docs and plugin details to reflect this and close this issue when complete

**Comment by knavesec** [comment]
Tagging all those above: @TwistedSim @alecmoran1 @LukeLauterbach @kpomeroy1979 @TheToddLuci0 

Would the community prefer this plugin be simply removed, have a big "WARNING" sign upon running (but still running as usual), or just run with an error message stating "this plugin is no longer supported, see MS docs: here"

**Comment by knavesec** [comment]
Repo updated to remove the `o365` plugin. `o365enum` still works so nothing touched there
[cf21775](https://github.com/knavesec/CredMaster/commit/cf21775ce6ad54a03f63ec9108649ef244a17cc6)
https://github.com/knavesec/CredMaster/wiki/O365
